@ToDoApi_HostAddress = https://localhost:7085

POST {{ToDoApi_HostAddress}}/todoitems/v2
Content-Type: application/json

{
  "name":"walk dog",
  "isComplete":true
}

###

GET {{ToDoApi_HostAddress}}/todoitems/v2

###

@id=1
GET {{ToDoApi_HostAddress}}/todoitems/v2/{{id}}

###

PUT {{ToDoApi_HostAddress}}/todoitems/v2/{{id}}
Content-Type: application/json

{
  "name": "feed fish",
  "isComplete": false
}

###

DELETE {{ToDoApi_HostAddress}}/todoitems/{{id}}

###
